### ISSUE TITLE
Issues regarding pathSets including integer-like values

### ISSUE THREAD

**Issue by LarsVonQualen** [Netflix/falcor-path-utils#9]
So i'm currently working on a project where we have defined multiple routes where we do something like {keys:productIds}, we does this because our productIds are string, but now and then we get id's that your isNumber checking function here https://github.com/Netflix/falcor-path-utils/blob/master/lib/toPaths.js#L218 falsely flags as numbers, it is string like this one "0123", which is to say an integer with leading zeros. This results in falcor, routes containing actual integers, routes we haven't defined, and do not intend to, because our id's are strings, so it wouldn't make sense.

I would like to propose a change that takes a more aggressive stance, in order to just enforce the number type, so the check would maybe look a bit more like this:
`typeof value === 'number' && isFinite(val) && val !== Infinity && val !== -Infinity`

**Comment by lrowe** [comment]
I agree that this is a problem. We should only collapse string keys losslessly, i.e. where `val === String(parseInt(val, 10))`. We need to work out what the fastest way to do this is in javascript across our various supported platforms, either a regex test `/^(0|(\-?[1-9][0-9]*))$/` or checking character in a loop.
